language: python

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt
  

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_one;" -U postgres

script: 
  - nosetests --with-coverage

after_success:
  - coveralls